image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: GitHub mirror
          script:
            - git push --mirror git@github.com:Adaptavist/terraform-compliance.git

